language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
  - pip install --editable .
script:
  - coverage run -m unittest
after_success:
  coveralls